"""Select a diverse >=N-tune v1 HVSC corpus and emit tests/_corpus.py.

Uses pysidtracker's ``resolve_tune`` to fetch candidates round-robin across a
broad composer set, keeps PSID tunes with a per-frame ``play`` driver (v1), and
writes the accepted relpaths as ``.sid`` literals for the fetch machinery.
"""

import re
import sys
import urllib.request
from collections import defaultdict
from pathlib import Path

from pysidtracker.testing import DEFAULT_MIRROR, TuneFetchError, resolve_tune

from deity_informant.c64 import load_psid

CACHE = Path(".oracle-cache/hvsc")
MANIFEST = Path("tests/_corpus.py")
TARGET = 128

COMPOSERS = [
    "H/Hubbard_Rob",
    "G/Galway_Martin",
    "F/Follin_Tim",
    "F/Follin_Geoff",
    "D/Daglish_Ben",
    "T/Tel_Jeroen",
    "T/Tel_Kees",
    "L/Laxity",
    "W/Walker_Martin",
    "D/Deenen_Charles",
    "G/Gray_Fred",
    "G/Gray_Matt",
    "D/Dunn_David",
    "M/Mahoney",
    "X/X-Jammer",
    "N/Norman_Paul",
    "C/Cadaver",
    "J/Jammer",
    "G/Goto80",
    "W/Whittaker_David",
    "H/Huelsbeck_Chris",
    "L/Linus",
    "V/Vibrants",
    "B/Bjerregaard_Johannes",
    "S/Steel",
    "R/Rowlands_Matt",
    "L/Liljedahl_Bjorn",
    "D/DRAX",
    "S/SounDemoN",
    "F/FAME",
    "S/Slaygon",
    "L/Lft",
]


def songlengths(cache=CACHE, mirror=DEFAULT_MIRROR):
    """Cached ``Songlengths.md5``, fetched from the mirror when absent."""
    dst = Path(cache) / "Songlengths.md5"
    if not dst.is_file():
        dst.parent.mkdir(parents=True, exist_ok=True)
        with urllib.request.urlopen("%s/DOCUMENTS/Songlengths.md5" % mirror, timeout=120) as fh:
            dst.write_bytes(fh.read())
    return dst


def candidates():
    """Round-robin MUSICIANS relpaths across the composer set (diversity first)."""
    by_comp = defaultdict(list)
    pat = re.compile(r"^; (/MUSICIANS/([A-Z]/[^/]+)/.+\.sid)$")
    for line in songlengths().read_text(encoding="latin-1").splitlines():
        m = pat.match(line)
        if m and m.group(2) in COMPOSERS:
            by_comp[m.group(2)].append(m.group(1).lstrip("/"))
    rels, i = [], 0
    while any(i < len(by_comp[c]) for c in COMPOSERS):
        rels += [by_comp[c][i] for c in COMPOSERS if i < len(by_comp[c])]
        i += 1
    return rels


def valid_v1(path):
    """A cached path is a v1 tune (PSID/RSID with a per-frame play driver)."""
    try:
        data = Path(path).read_bytes()
        if data[:4] not in (b"PSID", b"RSID"):
            return False
        return bool(load_psid(data)[3])
    except Exception:  # pylint: disable=broad-except
        return False


def main():
    if "--songlengths" in sys.argv:
        print("cached %s" % songlengths(), flush=True)
        return
    kept = []
    for rel in candidates():
        if len(kept) >= TARGET:
            break
        try:
            path = resolve_tune(rel, cache_dir=CACHE)
        except TuneFetchError:
            path = None
        if path and valid_v1(path):
            kept.append(rel)
            print("[%3d] %s" % (len(kept), rel), flush=True)
        elif path:
            Path(path).unlink(missing_ok=True)
    body = "".join('    "%s",\n' % r for r in sorted(kept))
    MANIFEST.write_text(
        '"""HVSC v1 corpus manifest: relpaths (not copyrighted), fetched on demand.\n\n'
        "Generated by tools/fetch_corpus.py; the .sid literals let pysidtracker\n"
        'pre-cache exactly this diverse >=128-tune set."""\n\n'
        "CORPUS = [\n" + body + "]\n",
        encoding="utf-8",
    )
    print("wrote %s with %d tunes" % (MANIFEST, len(kept)), flush=True)


if __name__ == "__main__":
    main()
