"""Regenerate out/<Tune>.tracker.txt: the tracker-layer view for review.

One file per showcase tune — lifted engine, per-voice note-lane runs, and any
Follin command-script lanes. Full Songlengths for correctness. out/ is gitignored.
"""

import multiprocessing as mp
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "tests"))

SHOWCASE = [
    "MUSICIANS/H/Hubbard_Rob/Commando.sid",
    "MUSICIANS/H/Hubbard_Rob/Monty_on_the_Run.sid",
    "MUSICIANS/G/Goto80/Automatas.sid",
    "MUSICIANS/D/Daglish_Ben/Krakout.sid",
    "MUSICIANS/D/Daglish_Ben/Trap.sid",
    "MUSICIANS/G/Galway_Martin/Athena.sid",
    "MUSICIANS/G/Galway_Martin/Wizball.sid",
    "MUSICIANS/F/Follin_Tim/Bionic_Commando.sid",
    "MUSICIANS/F/Follin_Tim/Ghouls_n_Ghosts.sid",
    "MUSICIANS/L/Laxity/Freeze.sid",
]


def _lane_runs(lane):
    """Collapse [(frame, Note)] into runs of equal note name with detune range."""
    runs = []
    for frame, note in lane:
        if runs and runs[-1][1] == note.name:
            runs[-1][3] += 1
            runs[-1][4] = min(runs[-1][4], note.detune)
            runs[-1][5] = max(runs[-1][5], note.detune)
        else:
            runs.append([frame, note.name, note.index, 1, note.detune, note.detune])
    return runs


def _engine_lines(t):
    """Human-readable engine block: pitch table, tempo, clocks."""
    out = []
    if t.pitch is None:
        out.append("pitch  (none recovered)")
    else:
        p = t.pitch
        mode = "1-octave shift" if p.shift else "%d-octave" % p.octaves
        lay = {">": "big-endian", "<": "little-endian", "split": "split lo/hi"}[p.endian]
        out.append("pitch  $%04X  %s  %s  words=%d" % (p.base, lay, mode, len(p.words)))
    out.append("tempo  frames_per_tick=%s" % ("$%04X" % t.tempo if t.tempo else "per-voice"))
    out.append("divisors  %s" % (", ".join(str(n) for n in t.divisors) or "(none declared)"))
    for c in t.clocks:
        out.append(
            "clock  $%04X  %s  %s%s"
            % (c.base, c.kind, c.role, "  reload=$%04X" % c.reload if c.reload else "")
        )
    return out


def render_tune(rel):
    """Decompile one tune full-length and write its out/<Tune>.tracker.txt."""
    from deity_informant import follin_script as fscript
    from deity_informant import framelog
    from deity_informant import frameprog
    from deity_informant import structured as S
    from deity_informant import tracker
    from deity_informant.c64 import load_psid

    from _corpus import corpus_params

    hvsc = ROOT / ".oracle-cache" / "hvsc"
    entry = next((t for t in corpus_params(hvsc) if str(t[0]).endswith(rel)), None)
    if entry is None:
        return "%s: not cached" % Path(rel).stem
    sid, sub, secs = entry
    mem, _load, init, play = load_psid(sid.read_bytes())
    mem[0xD418] = 0x0F
    frames = secs * 50
    model, _ev = S.decompile(mem, init, play, frames, sub)
    prog = frameprog.program(model)
    trace, _walker = frameprog.iota(model, frames)
    rendered, gt, cov, lanes = tracker.render(prog, trace, frames)
    div = framelog.diff(rendered, gt)  # the law, on the projection just rendered
    t = tracker.lift(prog, gt)
    scripts = fscript.decode(model)

    lines = ["tracker %s  (subtune %d, %d frames)" % (sid.stem, sub, frames), "; ---- engine ----"]
    lines += _engine_lines(t)
    lines.append("; ---- note lanes (frame  note  xcount  detune[lo..hi]) ----")
    fi, ft = cov.planes.get("freq", (0, 0))
    lines.append(
        "gate: %s   interpreted %d/%d writes (%.0f%%)   freq %d/%d (%.0f%%)"
        % (
            "PASS" if div is None else "FAIL %r" % (div,),
            cov.interp,
            cov.total,
            100.0 * cov.interp / max(cov.total, 1),
            fi,
            ft,
            100.0 * fi / max(ft, 1),
        )
    )
    lines.append(
        "residual planes: "
        + "  ".join(
            "%s %d/%d" % (p, it, tot) for p, (it, tot) in sorted(cov.planes.items()) if it < tot
        )
    )
    tg, tt = cov.triggers  # the trigger domain, reported apart from the value partition
    lines.append(
        "triggers: %d/%d fires generated by a DIV (%.1f%%)" % (tg, tt, 100.0 * tg / max(tt, 1))
    )
    for v in range(3):
        runs = _lane_runs(lanes[v])
        lines.append("V%d  (%d note-frames, %d runs)" % (v + 1, len(lanes[v]), len(runs)))
        for f, name, _idx, cnt, dlo, dhi in runs[:80]:
            det = "" if dlo == dhi == 0 else "  detune[%+d..%+d]" % (dlo, dhi)
            lines.append("  f%-6d %-4s x%-4d%s" % (f, name, cnt, det))
        if len(runs) > 80:
            lines.append("  ... (%d more runs)" % (len(runs) - 80))
    if scripts:
        lines.append("; ---- command-script lanes (Follin, certified vs reads) ----")
        for sc in scripts:
            lines.append(fscript.render(sc))
    (ROOT / "out" / ("%s.tracker.txt" % sid.stem)).write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )
    return "%s: pitch=%s interp=%d/%d scripts=%d gate=%s" % (
        sid.stem,
        t.pitch is not None,
        cov.interp,
        cov.total,
        len(scripts),
        "PASS" if div is None else "FAIL",
    )


def main():
    """Render all showcase tunes in parallel."""
    with mp.Pool(min(len(SHOWCASE), 10)) as pool:
        for row in pool.map(render_tune, SHOWCASE):
            print(row)


if __name__ == "__main__":
    main()
