"""Generate the SMC (self-modifying code) SLEIGH overlay for the 6510 module.

Emits ``6510_context.sinc`` (``noflow`` ``contextreg`` fields) and
``6510_smc.sinc``: constructors with an extra context constraint, hence more
specific than the stock ones, reading their operand from ``inst_start+1``.
"""

from __future__ import annotations

import re

PRE = "local smcp:2 = inst_start + 1; "
BYTE = "*:1 smcp"
WORD = "*:2 smcp"

CONTEXT = """# generated by ghidra/6510/smc.py -- do not edit
define register offset=0x40 size=4 [ contextreg ];
define context contextreg
  smc_imm  = (0,0) noflow
  smc_addr = (1,1) noflow
  smc_ctrl = (2,2) noflow
  smc_var  = (3,3) noflow
;
"""

# mode -> (display, extra pattern, semantics reading the operand live)
MODES = {
    "imm": ('"#"imm8', "", "tmp:1 = %s; export tmp;" % BYTE),
    "zp": ("imm8", "", "tmp:2 = zext(%s); export *:1 tmp;" % BYTE),
    "zpx": ("imm8,X", " & X", "tmp:2 = zext(%s + X); export *:1 tmp;" % BYTE),
    "zpy": ("imm8,Y", " & Y", "tmp:2 = zext(%s + Y); export *:1 tmp;" % BYTE),
    "abs": ("imm16", "", "tmp:2 = %s; export *:1 tmp;" % WORD),
    "absx": ("imm16,X", " & X", "tmp:2 = %s + zext(X); export *:1 tmp;" % WORD),
    "absy": ("imm16,Y", " & Y", "tmp:2 = %s + zext(Y); export *:1 tmp;" % WORD),
    "indx": ("(imm8,X)", " & X", "addr:2 = zext(%s + X); tmp:2 = *:2 addr; export *:1 tmp;" % BYTE),
    "indy": (
        "(imm8),Y",
        " & Y",
        "addr:2 = zext(%s); tmp:2 = *:2 addr; tmp = tmp + zext(Y); export *:1 tmp;" % BYTE,
    ),
}

TOKEN = {m: ("imm16" if m in ("abs", "absx", "absy") else "imm8") for m in MODES}

# subtable -> {bbb: mode}; OP2ST/OP2LD list only what they add over OP2.
SUBTABLES = {
    "OP1": {0: "indx", 1: "zp", 2: "imm", 3: "abs", 4: "indy", 5: "zpx", 6: "absy", 7: "absx"},
    "OP2": {0: "imm", 1: "zp", 3: "abs", 5: "zpx", 7: "absx"},
    "OP2ST": {5: "zpy"},
    "OP2LD": {5: "zpy", 7: "absy"},
    "OP3": {0: "indx", 1: "zp", 3: "abs", 4: "indy", 5: "zpx", 6: "absy", 7: "absx"},
}

# opcode -> (mnemonic, condition under which the branch falls through)
BRANCHES = {
    0x10: ("BPL", "N"),
    0x30: ("BMI", "N == 0"),
    0x50: ("BVC", "V"),
    0x70: ("BVS", "V == 0"),
    0x90: ("BCC", "C"),
    0xB0: ("BCS", "C == 0"),
    0xD0: ("BNE", "Z"),
    0xF0: ("BEQ", "Z == 0"),
}

# smc_var=1 -- opcode cell whose other variant is the 1-byte terminator $60.
RTS_GUARD = (
    "if (*:1 (smcp - 1) != 0x60) goto <base>; "
    "SP = SP + 1; rt:2 = *:2 SP; SP = SP + 1; return [rt]; <base> "
)


def _operand_lines():
    """Context-selected addressing-mode constructors for every operand subtable."""
    out = []
    for sub, modes in SUBTABLES.items():
        for bbb, mode in sorted(modes.items()):
            disp, extra, body = MODES[mode]
            bit = "smc_imm" if mode == "imm" else "smc_addr"
            pat = "bbb=%d%s; %s" % (bbb, extra, TOKEN[mode])
            out.append("%s: %-10s is %s=1 & %s { %s%s }" % (sub, disp, bit, pat, PRE, body))
            out.append(
                "%s: %-10s is smc_var=1 & %s { %s%s%s }" % (sub, disp, pat, PRE, RTS_GUARD, body)
            )
    out.append(
        "ADDRI: (imm16) is smc_addr=1 & imm16 { %stmp:2 = %s; export *:2 tmp; }" % (PRE, WORD)
    )
    return out


def _control_lines():
    """``JMP``/``JSR``/branch constructors whose target byte(s) are a cell."""
    out = [
        ":JMP imm16 is smc_ctrl=1 & op=0x4C; imm16 { %slocal t:2 = %s; goto [t]; }" % (PRE, WORD),
        ":JSR imm16 is smc_ctrl=1 & op=0x20; imm16 "
        "{ %s*:2 (SP-1) = inst_next; SP = SP-2; local t:2 = %s; call [t]; }" % (PRE, WORD),
    ]
    out += [
        ":%s rel is smc_ctrl=1 & op=0x%02X; rel { %slocal t:2 = inst_next + sext(%s); "
        "if (%s) goto <fall>; goto [t]; <fall> }" % (mn, op, PRE, BYTE, cond)
        for op, (mn, cond) in sorted(BRANCHES.items())
    ]
    return out


def _blocks(text):
    """Every top-level ``:MNEM ... { body }`` constructor of ``text``, verbatim."""
    out, cur, depth = [], None, 0
    for line in text.splitlines():
        if cur is None:
            if not line.startswith(":"):
                continue
            cur = []
        cur.append(line)
        depth += line.count("{") - line.count("}")
        if depth == 0 and "{" in "\n".join(cur):
            out.append("\n".join(cur))
            cur = None
    return out


def _operand_size(disp, token):
    """Bytes of the local replacing ``token``: 2 where the body assigns it to an address."""
    return 2 if token == "imm16" or disp in ("imm8", "(imm8),Y") else 1


def _twin(block):
    """The SMC twin of one explicit-opcode illegal constructor, or ``None``."""
    head, body = block.split("{", 1)
    body = body.rsplit("}", 1)[0]
    sig, pattern = head.split(" is ", 1)
    pattern, _, operands = pattern.partition(";")
    token = operands.strip()
    if token not in ("imm8", "imm16"):
        return None
    parts = sig.split(None, 1)
    disp = parts[1].strip() if len(parts) > 1 else ""
    size = _operand_size(disp, token)
    expr = "zext(%s)" % BYTE if size == 2 and token == "imm8" else (WORD if size == 2 else BYTE)
    return "%s is %s & smc_%s=1; %s {\n    %slocal smcop:%d = %s;%s}" % (
        sig.rstrip(),
        pattern.strip(),
        "imm" if '"#"' in disp else "addr",
        token,
        PRE,
        size,
        expr,
        re.sub(r"\b%s\b" % token, "smcop", body),
    )


def illegal_twins(text):
    """SMC twins for every illegal constructor that spells out its own operand."""
    return [t for t in (_twin(b) for b in _blocks(text)) if t]


def smc_sinc(illegal_text):
    """The generated ``6510_smc.sinc`` body."""
    return "\n".join(
        ["# generated by ghidra/6510/smc.py -- do not edit", ""]
        + _operand_lines()
        + [""]
        + _control_lines()
        + ["", "# illegal opcodes with an inline operand"]
        + illegal_twins(illegal_text)
        + [""]
    )


BORROW = "(result & complement_register)) & 0b10000000 ) %s 0;"
# stock JSR/RTS push and return to inst_next, one byte off hardware
PATCHES = (
    (":JSR", "inst_next;", "inst_next - 1;"),
    (":RTS", "return [tmp];", "return [tmp+1];"),
    # stock leaves SBC's C the borrow, the 6510's complement (ghidra#3189);
    ("macro subtraction_flags1", BORROW % "!=", BORROW % "=="),  # ISC/SBX share it
)


def _in_ctor(text, head, old, new):
    """Replace ``old`` inside the constructor or macro starting with ``head`` only."""
    i = text.find("\n" + head)
    j = text.find("\n}", i)
    if i < 0 or j < 0 or old not in text[i:j]:
        return text
    return text[:i] + text[i:j].replace(old, new, 1) + text[j:]


def patch_base(base_text):
    """``base_text`` with the context include and the hardware stack/borrow rules."""
    lines = base_text.splitlines()
    i = max(n for n, l in enumerate(lines) if l.startswith("define register"))
    lines.insert(i + 1, '@include "6510_context.sinc"')
    text = "\n".join(lines) + "\n"
    for head, old, new in PATCHES:
        text = _in_ctor(text, head, old, new)
    return text
